# Generated by Django 3.2.8 on 2021-10-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetails',
            name='paid_method',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='percentage_of_work_complete',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='type_of_service',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
